# YAML configuration file for Docker Compose version 3.8
version: '3.8'

# Define services
services:

  # Database service using PostgreSQL image
  database:
    image: postgres:latest  # Use the latest PostgreSQL image from Docker Hub
    environment:
      POSTGRES_DB: LKRental  # Define the name of the database
      POSTGRES_USER: postgres    # Define the username for accessing the database
      POSTGRES_PASSWORD: longprobi1  # Define the password for the user
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data  # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL

  # Backend service
  backend:
    build: . # Build the Docker image using the Dockerfile in the current directory
    image: LKRental/backend
    ports:
      - "3000:3000"  # Forward the container's port 3000 to the host machine's port 3000 for accessing the backend service
    depends_on:
      - database  
    env_file:
      - .env  

# Define named volumes
volumes:
  database:
